'use client';
import bodyLogos from '@/data/body-logos.json';
import socialSources from '@/data/social-sources.json';
import {professionalTopics} from '@/lib/professional-topics';
import {professionalBodies,belongsToBody} from '@/lib/professional-bodies';
import AppNotifications from './app-notifications';
import {useEffect,useMemo,useState} from 'react';
import {BookOpen,Search,FileText,Newspaper,ArrowUpRight,ArrowRight,ShieldCheck,X,Archive,Globe2,House,ChevronRight,BadgeCheck,TrendingUp,Award} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {regions,regionName,selectNews,dateLabel,sectionHighlights,indiaToday,type News,type View} from '@/lib/news-model';
export type {News} from '@/lib/news-model';
const logoPath=(id:string)=>'/logos/'+id+(['india','uk'].includes(id)?'.png':'.svg');
const topicIcon=(id:string)=>id==='quality'?<BadgeCheck/>:id==='excellence'?<TrendingUp/>:<Award/>;
type Status={topicChecks?:Record<string,string>;topicCoverage?:Record<string,string>;checkedAt:string;scheduleEnabled:boolean;coverage:string;regionChecks?:Record<string,string>};
export default function Newsroom({initialNews,status,view={kind:'home'}}:{initialNews:News[];status:Status;view?:View}){
 const [news,setNews]=useState(initialNews),[loading,setLoading]=useState(initialNews.length===0),[tab,setTab]=useState('official'),[query,setQuery]=useState(''),[limit,setLimit]=useState(20),[archiveError,setArchiveError]=useState(''),[certFilter,setCertFilter]=useState('all');
 useEffect(()=>{fetch('/api/news').then(async r=>{if(!r.ok)throw Error();const d=await r.json() as {news?:News[]};if(!Array.isArray(d.news)||!d.news.every(n=>n&&['id','title','url','published','summary','category','source','tab'].every(k=>typeof n[k as keyof News]==='string')))throw Error();setNews(d.news)}).catch(()=>setArchiveError('The live archive is temporarily unavailable. Please try again.')).finally(()=>setLoading(false));},[]);
 const [automatic,setAutomatic]=useState<{active?:boolean;lastSuccessfulAt?:string;lastAttemptAt?:string;checks?:{name:string;tab:string;region:string;status:string;items:number;detail:string}[]}|null>(null);
 useEffect(()=>{fetch('/api/updater').then(r=>r.ok?r.json():null).then(d=>setAutomatic(d as typeof automatic)).catch(()=>{});},[]);
 const [today,setToday]=useState(()=>indiaToday());
 useEffect(()=>{const timer=setInterval(()=>setToday(indiaToday()),60000);return()=>clearInterval(timer)},[]);
 const isBlogs=view.kind==='blogs';
 const topic=professionalTopics.find(t=>t.id===view.topic),isTopic=view.kind==='topic';
 const body=professionalBodies.find(b=>b.id===view.body&&b.topics.includes(view.topic||'')),isTopicHub=isTopic&&!body;
 const country=regions.find(r=>r.id===view.region),isCountry=view.kind==='country',isFeed=view.kind==='feed',isHub=!isCountry&&!isFeed&&!isTopic&&!isBlogs;
 const scope=isCountry?view.region!:(isFeed?view.region!:'all');
 const kind=isBlogs?'blogs':isTopic?view.topic!:isCountry?(view.region==='india'?'official':tab):view.kind==='regulatory'?'regulatory':(isFeed||view.kind==='news'?'news':'all');
 const filtered=useMemo(()=>selectNews(news,scope,kind,query).filter(n=>!body||belongsToBody(n,body)).filter(n=>!isTopic||view.topic!=='certifications'||certFilter==='all'||n.category.toLowerCase().startsWith(certFilter)),[news,scope,kind,query,isTopic,view.topic,certFilter,body]);
 const heading=isBlogs?'Blogs':isTopic?(body?.name||topic!.title):isCountry?`${country?.name} · ${country?.id==='india'?'FSSAI':country?.id==='us'?'US FDA':'Food regulation'}`:isFeed?(view.region==='india'?'India food safety news':'Global food safety news'):view.kind==='updates'?'Food Safety/Quality Updates':view.kind==='regulatory'?'Regulatory updates':view.kind==='news'?'Food safety news':'Home';
 const subtitle=isBlogs?'Food safety, quality and process excellence · Pragash Ramadoss':isTopic?(body?.description||topic!.detail):isCountry?country!.detail:isFeed?(view.region==='india'?'Inspections, enforcement, recalls and court developments from across India.':'Food safety stories from outside India, together in one global feed.'):view.kind==='updates'?'Regulatory, food safety, quality, process excellence, certification and blog updates in one place.':view.kind==='regulatory'?'Choose a country or region to explore official updates and food safety news.':view.kind==='news'?'Follow developments in India or explore food safety news outside India.':'Your daily food safety, quality and excellence workspace.';

 function Recent({items,label}:{items:News[];label:string}){
  const latest=sectionHighlights(items,view,today);
  return <section className="home-recent section-recent" aria-label={'Latest updates · '+label}><h2>Latest updates <span>{label}</span></h2><p className="latest-rule">All updates from the latest publication day · Recent stories included when fewer than 3 · India time</p>{archiveError&&<p className="notice" role="status">{archiveError}</p>}{loading&&latest.length===0?<p className="notice" role="status">Loading latest updates…</p>:<><div className="home-recent-list">{latest.map(n=><a key={n.id} href={n.url} target="_blank" rel="noopener noreferrer"><span><small>{n.source} · <time dateTime={n.published}>{dateLabel(n.published)}</time>{n.published===today?' · Today':''}</small><strong>{n.title}</strong></span><ArrowUpRight size={18} aria-hidden="true"/><span className="sr-only">Opens original source in a new tab</span></a>)}</div>{latest.length===0&&<p>No verified updates available yet.</p>}</>}</section>;
 }
 function Cards(){return <><div className="feed-heading"><h2>{query?'Search results':isCountry?(tab==='official'?'Official updates':'Food safety news'):'Latest stories'}</h2><span>{filtered.length} {filtered.length===1?'item':'items'} · Newest first</span></div>{archiveError&&<p className="notice" role="status">{archiveError}</p>}
 {filtered.length===0?<div className="empty-state"><Search size={28}/><h3>{loading?'Loading latest updates…':query?'No matching stories':'No verified updates available yet'}</h3><p>{loading?'Connecting to the WordPress news archive.':query?'Try a different keyword. Use Home to search across all regions.':'New items will appear after a successful source check. Earlier stories are kept when a source has no new updates.'}</p>{query&&!loading&&<button className="text-button" onClick={()=>setQuery('')}>Clear search</button>}</div>:filtered.slice(0,Math.max(limit,filtered.filter(n=>n.published===today).length)).map((n,i)=><article className={'news-card '+(i===0&&!query?'lead-card':'')} key={n.id}><div className="card-meta"><div className="story-labels"><span className={'category '+(n.category.toLowerCase().includes('court')?'court':'')}>{n.category}</span>{(scope==='all'||scope==='global')&&<span className="story-region">{regionName(n.region||'india')}</span>}</div><time dateTime={n.published}>{dateLabel(n.published)}</time></div><h3><a href={n.url} target="_blank" rel="noopener noreferrer">{n.title}</a></h3>{n.summary&&<p className="summary">{n.summary}</p>}<div className="card-bottom"><span className="source"><span className="source-symbol">{n.tab==='fssai'&&regions.some(r=>r.id===(n.region||'india'))?<img src={logoPath(n.region||'india')} alt=""/>:<Newspaper size={18}/>}</span><span>{n.source}<small>{n.sourceType}</small></span></span><a className="read-link" href={n.url} target="_blank" rel="noopener noreferrer">{n.url.toLowerCase().includes('.pdf')?'Read document':'Read original'}<ArrowUpRight size={17}/><span className="sr-only">: {n.title} (opens in a new tab)</span></a></div></article>)}{filtered.length>Math.max(limit,filtered.filter(n=>n.published===today).length)&&<button className="load-more" onClick={()=>setLimit(x=>Math.max(x,filtered.filter(n=>n.published===today).length)+20)}>Show more updates <span>{filtered.length-Math.max(limit,filtered.filter(n=>n.published===today).length)} remaining</span></button>}</>}
 const feed=<div className="content-layout"><section className="feed" aria-label={heading}><Cards/></section><aside className="side-column"><div className="desk-card"><span className="desk-icon">{isCountry?<img className="desk-logo" src={logoPath(country?.id||'india')} alt={country?.agency+' logo'}/>:<Globe2 size={23}/>}</span><h3>{isCountry?country?.agency:'Stories with sources'}</h3><p>{isCountry?'Read each notice in its original context. A consultation or scientific assessment does not itself establish a new legal requirement.':'Every headline opens the specific article, official announcement or social post. Dates show when the source published the story.'}</p><div className="desk-stat"><span>Latest publication in this feed</span><strong>{filtered[0]?dateLabel(filtered[0].published):'Awaiting sources'}</strong></div></div><div className="archive-note"><Archive size={20}/><div><h3>Nothing new? Nothing lost.</h3><p>Earlier updates stay in the archive when no new news is published.</p></div></div><div className="coverage"><h3>Source coverage</h3><p>{isTopic?status.topicCoverage?.[view.topic!]||'Selected official sources; coverage varies.':status.coverage}</p><p className="schedule-note">{automatic?.active?'Automatic collection is running through GitHub and WordPress. Coverage varies by source.':status.scheduleEnabled?'Daily checks scheduled through GitHub. Source availability and coverage vary.':'Daily scheduling is being configured.'}</p></div></aside></div>;
 return <div className={"app-shell app-dashboard"+(view.kind==='home'?' compact-home':'')}><header className="masthead"><a className="brand" href="/" aria-label="PMSV Food Safety Updates home"><span className="brand-mark family-brand"><img src="/brand/pmsv-family.png" alt="PMSV family logo"/></span><div><div className="brand-name">PMSV <span>Food Safety Updates</span></div><div className="brand-sub">FOOD SAFETY · QUALITY · EXCELLENCE</div></div></a><AppNotifications/></header>
 <nav className="primary-nav" aria-label="Main navigation"><div className="nav-caption">WORKSPACE</div><a href="/" aria-current={view.kind==='home'?'page':undefined}><House size={17}/>Home</a><a href="/regulatory" aria-current={view.kind==='regulatory'||isCountry?'page':undefined}><ShieldCheck size={17}/>Regulatory</a><a href="/news" aria-current={view.kind==='news'||isFeed?'page':undefined}><Newspaper size={17}/><span className="desktop-nav-label">Food safety news</span><span className="mobile-nav-label">News</span></a>{professionalTopics.map(t=><a href={'/'+t.id} key={t.id} aria-current={view.topic===t.id?'page':undefined}>{topicIcon(t.id)}{t.short}</a>)}<a href="/blogs" aria-current={isBlogs?'page':undefined}><BookOpen size={17}/>Blogs</a><div className="nav-regions"><div className="nav-caption">REGULATORY DESKS</div>{regions.map(r=><a href={'/regulatory/'+r.id} key={r.id} aria-current={isCountry&&view.region===r.id?'page':undefined}><span className="nav-logo"><img src={logoPath(r.id)} alt=""/></span>{r.name}</a>)}</div><div className="nav-bottom"><img className="sidebar-family-logo" src="/icons/pmsv-family-192.png" alt="PMSV family logo"/><span>PMSV<small>Food safety, quality & excellence</small></span></div></nav>
 <main>{view.kind!=='home'&&<nav className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight size={14}/>{isCountry?<><a href="/regulatory">Regulatory</a><ChevronRight size={14}/><span>{country?.name}</span></>:isFeed?<><a href="/news">Food safety news</a><ChevronRight size={14}/><span>{view.region==='india'?'India':'Global'}</span></>:body?<><a href={'/'+view.topic}>{topic?.short}</a><ChevronRight size={14}/><span>{body.name}</span></>:<span>{heading}</span>}</nav>}
 {!isBlogs&&automatic?.lastAttemptAt&&<details className="official-directory"><summary>Automatic source checks · {new Date(automatic.lastAttemptAt).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}</summary><p>Only dated articles that can be read automatically are added. Social media and court coverage are not exhaustive. Last successful collection: {automatic.lastSuccessfulAt?new Date(automatic.lastSuccessfulAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not yet confirmed'}.</p>{automatic.checks?.map(c=><p key={c.name}><strong>{c.name}</strong>: {c.status==='ok'?'Checked':c.status==='partial'?'Partial coverage':'Needs review'} · {c.items} dated items · {c.detail}</p>)}</details>}<div className="heading-row"><div><p className="eyebrow">{isCountry?'COUNTRY & REGION DESK':isFeed?'THE NEWS DESK':'PMSV FOOD SAFETY UPDATES'}</p><h1>{heading}</h1><p className="intro">{subtitle}</p></div></div>
 {(!isBlogs||filtered.length>0||query)&&<label className="searchbox"><Search size={21}/><input type="search" aria-label="Search news updates" placeholder={isHub?'Search all topics, countries, regulators and news…':'Search this feed by topic, organisation or date…'} value={query} onChange={e=>{setQuery(e.target.value);setLimit(20)}}/>{query&&<button onClick={()=>{setQuery('');setLimit(20)}} aria-label="Clear search"><X size={18}/></button>}<span className="search-hint">{isHub?'SEARCH THE ARCHIVE':'SEARCH THIS FEED'}</span></label>}
 {(view.kind==='news'||(isFeed&&view.region==='india'))&&<details className="official-directory"><summary>FSSAI and state social sources · coverage</summary><p>Official social posts appear in India News. FSSAI website releases are in Regulatory. Public timelines can be incomplete; Instagram and Facebook currently expose no verifiable dated posts to our collector. This is selected state/UT coverage, not every department.</p>{socialSources.map(s=><p key={s.name}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.name}</a> · {s.items?`${s.items} posts extracted in the access test`:'No verifiable posts extracted'} · {dateLabel(s.checkedAt.slice(0,10))}</p>)}<p>See Automatic source checks for results from the daily collector.</p></details>}
 {isTopic&&<>{isTopicHub&&<nav className="professional-grid" aria-label={topic!.short+' bodies'}>{professionalBodies.filter(b=>b.topics.includes(view.topic!)).map(b=><a href={'/'+view.topic+'/'+b.id} key={b.id}><span className="body-logo"><img src={bodyLogos[b.name as keyof typeof bodyLogos].image} alt={b.name+' logo'} referrerPolicy="no-referrer" loading="lazy"/></span><strong>{b.name}</strong><small>{selectNews(news,'all',view.topic).filter(n=>belongsToBody(n,b)).length} updates</small></a>)}</nav>}{body&&<a className="body-official" href={body.url} target="_blank" rel="noopener noreferrer">Official {body.name} website <ArrowUpRight size={16}/></a>}{view.topic==='certifications'&&<Tabs value={certFilter} onValueChange={v=>{setCertFilter(v);setLimit(20)}}><TabsList className="news-tabs cert-tabs" aria-label="Certification subject">{['all','quality','food safety','excellence'].map(c=><TabsTrigger key={c} value={c}>{c==='all'?'All updates':c==='food safety'?'Food safety':c[0].toUpperCase()+c.slice(1)}</TabsTrigger>)}</TabsList></Tabs>}{isTopicHub&&!query&&<Recent items={filtered} label={topic?.short||heading}/>}</>}
 {isHub&&!query&&<>{view.kind==='home'?<><nav className="home-launcher home-primary-launcher" aria-label="PMSV tools"><a href="/updates"><span className="launch-icon launch-news"><Newspaper aria-hidden="true"/></span><strong>Food Safety/Quality<br/>Updates</strong></a><a href="/audits/index.html"><span className="launch-icon launch-audits"><ShieldCheck aria-hidden="true"/></span><strong>Food Safety/Quality<br/>Audit Checklists</strong></a></nav><Recent items={selectNews(news)} label="All sections"/></>:view.kind==='updates'?<><nav className="home-launcher" aria-label="Update sections"><a href="/regulatory"><span className="launch-icon launch-regulatory"><ShieldCheck aria-hidden="true"/></span><strong>Regulatory</strong></a><a href="/news"><span className="launch-icon launch-news"><Newspaper aria-hidden="true"/></span><strong>Food safety<br/>news</strong></a>{professionalTopics.map(t=><a href={'/'+t.id} key={t.id}><span className={'launch-icon launch-'+t.id}>{topicIcon(t.id)}</span><strong>{t.id==='excellence'?<>Process<br/>excellence</>:t.short}</strong></a>)}<a href="/blogs"><span className="launch-icon launch-blogs"><BookOpen aria-hidden="true"/></span><strong>Blogs</strong></a></nav><Recent items={selectNews(news)} label="All sections"/></>:view.kind==='regulatory'?<div className="region-grid">{regions.map(r=><a key={r.id} className="region-card" href={'/regulatory/'+r.id}><span className="regulator-logo"><img src={logoPath(r.id)} alt={r.agency+' logo'}/></span><div><h2>{r.name}</h2><h3>{r.agency}</h3><p>{r.description}</p></div><div className="region-bottom"><span>{selectNews(news,r.id,'official').length} official · {selectNews(news,r.id,'news').length} news</span><ArrowRight size={19}/></div></a>)}</div>:<div className="home-options"><a className="home-option" href="/news/india"><span className="region-code india"><img src="/logos/india.png" alt="FSSAI logo"/></span><h2>India news</h2><p>Food safety actions, official announcements and reporting from across India.</p><div className="option-bottom"><span>{selectNews(news,'india','news').length} stories</span><ArrowRight size={23}/></div></a><a className="home-option news-option" href="/news/global"><span className="option-icon"><Globe2 size={33}/></span><h2>Global news</h2><p>Food safety developments from outside India.</p><div className="option-bottom"><span>{selectNews(news,'global','news').length} stories</span><ArrowRight size={23}/></div></a></div>}{view.kind!=='home'&&view.kind!=='updates'&&<Recent items={filtered} label={heading}/>} {view.kind!=='home'&&<div className="hub-footnote"><Archive size={18}/><span>Updated daily. Earlier stories stay available. Every story links to its original source.</span></div>}</>}
 {isBlogs&&news.every(n=>n.tab!=='blogs')&&<section className="blog-empty"><span className="launch-icon launch-blogs"><BookOpen aria-hidden="true"/></span><h2>Pragash’s blog</h2><p>No blog posts have been imported yet. Published WordPress posts appear after the next successful daily check.</p><p>Each article will link to the original post.</p><a className="body-official" href="https://pragashramadoss-hlxqw.wordpress.com" target="_blank" rel="noopener noreferrer">Visit Pragash’s WordPress blog <ArrowUpRight size={16}/></a></section>}
 {isCountry&&view.region==='india'?<><a className="body-official" href="/news/india">FSSAI and state department social news → India News</a>{feed}</>:isCountry?<Tabs value={tab} onValueChange={v=>{setTab(v);setLimit(20)}}><TabsList className="news-tabs" aria-label="Country updates"><TabsTrigger value="official"><FileText/>Official updates<span className="count">{selectNews(news,scope,'official').length}</span></TabsTrigger><TabsTrigger value="news"><Newspaper/>Food safety news<span className="count">{selectNews(news,scope,'news').length}</span></TabsTrigger></TabsList><TabsContent value={tab}>{feed}</TabsContent></Tabs>:((!isHub&&!isTopicHub&&(!isBlogs||news.some(n=>n.tab==='blogs')))||query)?feed:null}
 </main><footer>{view.kind==='home'?<span>Daily updates · Official sources</span>:<><strong>PMSV Food Safety Updates</strong><span>Independent of the regulators and organisations listed. Read the original source for the authoritative text.</span></>}<span className="footer-links"><a href="/about">About us</a><a href="/privacy">Privacy & support</a></span></footer></div>
}
