import ts from 'typescript';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const source=await fs.readFile('lib/github-updater-auth.ts','utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
const {validUpdaterClaims,authorizedUpdater}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const now=Date.now()/1000;
const claims={iss:'https://token.actions.githubusercontent.com',aud:'pmsv-updater',repository:'pragashramadoss/pmsv-updater',repository_id:'1370842496',repository_owner_id:'329360973',ref:'refs/heads/main',workflow_ref:'pragashramadoss/pmsv-updater/.github/workflows/update.yml@refs/heads/main',event_name:'schedule',exp:now+300,nbf:now-10,iat:now-10};
assert.ok(validUpdaterClaims(claims));
for(const bad of [{repository_id:'other'},{repository_owner_id:'other'},{ref:'refs/heads/fork'},{workflow_ref:'other'},{aud:'other'},{exp:now-1},{iat:now-900},{event_name:'pull_request'}])assert.equal(validUpdaterClaims({...claims,...bad}),false);
assert.equal(await authorizedUpdater(new Request('https://example.org')),false);
assert.equal(await authorizedUpdater(new Request('https://example.org',{headers:{authorization:'Bearer fake.token.signature'}})),false);
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const jwk=await crypto.subtle.exportKey('jwk',pair.publicKey);jwk.kid='test-key';
globalThis.fetch=async()=>Response.json({keys:[jwk]});
const h=Buffer.from(JSON.stringify({alg:'RS256',kid:'test-key'})).toString('base64url'),p=Buffer.from(JSON.stringify(claims)).toString('base64url');
const sig=Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(h+'.'+p))).toString('base64url');
assert.equal(await authorizedUpdater(new Request('https://example.org',{headers:{authorization:'Bearer '+h+'.'+p+'.'+sig}})),true);
assert.equal(await authorizedUpdater(new Request('https://example.org',{headers:{authorization:'Bearer '+h+'.'+p+'.'+sig.slice(0,-4)+'AAAA'}})),false);
console.log('Updater authorization: trusted signed token accepted; altered signature, wrong repo/owner/branch/workflow/audience/events and expired tokens rejected.');
